const faker = require('faker');
const Product = require('../model/products.model');
const products = [
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 125,
    price: 100,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1205,
    price: 1000,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1225,
    price: 1100,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1855,
    price: 1220,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1205,
    price: 1000,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1245,
    price: 1080,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1525,
    price: 1005,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1250,
    price: 1000,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 2510,
    price: 2000,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 2100,
    price: 2000,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 925,
    price: 800,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 855,
    price: 800,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 625,
    price: 400,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1425,
    price: 1200,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },
  {
    name: faker.commerce.productName(),
    image: faker.random.image(),
    mrp: 1225,
    price: 1120,
    inStock: faker.random.boolean(),
    fastDelivery: faker.random.boolean(),
    ratings: faker.random.arrayElement([1, 2, 3, 4, 5]),
    offer: faker.random.arrayElement([
      "Save 50",
      "70% bonanza",
      "Republic Day Sale",
    ]),
  },

];

const addToProducts = (product)=>{
  const addedProd = Product.create({...product})
  console.log({addedProd}); 
}

module.exports = {products,addToProducts};